/**
 * The /api/emails router — the community email directory.
 *
 * The website owns the record so it can show the directory and join it to the
 * roster; the bot's `/email` command writes and reads it over these endpoints,
 * the same shape `/bgcheck` uses.
 *
 *   POST /bot            a member sets their own email (Gmail only). Anyone may.
 *   GET  /bot/search     which member an address belongs to. Needs emails.view.
 *   GET  /bot/:discordId a member's email on file. Needs emails.view.
 *   GET  /               the whole directory, for the site. Needs emails.view.
 *
 * "Needs emails.view" is decided here off the *caller's* live Discord roles (for
 * the bot routes) or their session (for the site), so the bot never reimplements
 * the permission model. emails.view resolves to Directorship and up. Adding your
 * own email needs nothing — it is your address, keyed to your own id.
 *
 * The tables are created on demand, like the leadership table, so a deploy that
 * has not re-run the schema still works.
 */
import { Router } from "express";
import { query, execute } from "../db.js";
import { loadGrants, requirePermission } from "../middleware/requirePermission.js";
import { withOwnerOverride } from "../middleware/requireRole.js";
import { permissionsFor } from "../permissions.js";
import { requireBot } from "../middleware/requireBot.js";
import { fetchMemberRoles } from "../lib/discord.js";
import { resolveRoleKeys } from "../lib/roleSync.js";
import { DEPARTMENT_COMMAND_KEYS } from "../lib/discipline.js";
import { str } from "../validate.js";
import * as seed from "../rosterSeed.js";

/** The department-head role keys (fhp_colonel, bcso_sheriff, mpd_chief). */
const DEPT_HEAD_KEYS = Object.values(DEPARTMENT_COMMAND_KEYS);

const router = Router();

/** Only Gmail addresses are accepted. Case-insensitive on the domain. */
const GMAIL_RE = /^[a-zA-Z0-9._%+-]+@gmail\.com$/i;

let tablesReady = false;
async function ensureTables() {
  if (tablesReady) return;
  await query(`CREATE TABLE IF NOT EXISTS member_emails (
    discord_id  VARCHAR(20)  NOT NULL,
    email       VARCHAR(320) NOT NULL,
    name        VARCHAR(128) NULL,
    updated_at  TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_at  TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (discord_id)
  )`);
  await query(`CREATE TABLE IF NOT EXISTS member_email_history (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY,
    discord_id  VARCHAR(20)  NOT NULL,
    email       VARCHAR(320) NOT NULL,
    replaced_at TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id)
  )`);
  await query("CREATE INDEX IF NOT EXISTS idx_member_email_history ON member_email_history (discord_id, replaced_at DESC)");
  await query("CREATE INDEX IF NOT EXISTS idx_member_emails_email ON member_emails (LOWER(email))");
  tablesReady = true;
}

/**
 * Whether the Discord user who invoked a lookup (`/email check` / `/email search`)
 * may read an email off the record.
 *
 * Off their live main-guild roles, exactly as the DA Hub authorises `/bgcheck`, so
 * the answer can never disagree with the site. Two ways in: holding `emails.view`
 * (Directorship+, who also read the whole directory on the site), or being a
 * department head — command may look a member up without the site-wide grant, the
 * same shape department command file DAs without `discipline.file`. Fails closed.
 */
async function actorMayViewEmails(actorDiscordId) {
  if (!/^\d{17,20}$/.test(actorDiscordId)) return false;
  try {
    const membership = await fetchMemberRoles(actorDiscordId);
    if (membership === null) return false; // not in the guild
    const roleKeys = withOwnerOverride(actorDiscordId, await resolveRoleKeys(membership.roles));
    const permissions = permissionsFor(roleKeys, await loadGrants());
    if (permissions.has("emails.view")) return true;
    const held = new Set(roleKeys);
    return DEPT_HEAD_KEYS.some((key) => held.has(key));
  } catch {
    return false;
  }
}

function forbiddenLookup(res) {
  return res.status(403).json({
    ok: false,
    code: "AUTH_ROLE_MISSING",
    message: "You don't have permission to read the email directory.",
  });
}

/* ------------------------------------------------------------------ *
 * The bot
 * ------------------------------------------------------------------ */

/** A member sets their own email. Keyed to the id the caller passes — the bot only
 *  ever sends the invoking user's own id — so there is no "on behalf of". */
router.post("/bot", requireBot, async (req, res) => {
  const discordId = str(req.body?.discordId).trim();
  const email = str(req.body?.email).trim();
  const name = str(req.body?.name).slice(0, 128).trim() || null;

  if (!/^\d{17,20}$/.test(discordId)) {
    return res.status(400).json({ ok: false, message: "That is not a Discord ID." });
  }
  if (!GMAIL_RE.test(email)) {
    return res.status(400).json({ ok: false, code: "BAD_EMAIL", message: "A Gmail address is required." });
  }

  try {
    await ensureTables();
    const existing = (await query("SELECT email FROM member_emails WHERE discord_id = $1", [discordId]))[0];
    const previous = existing?.email ?? null;
    const changed = Boolean(previous) && previous.toLowerCase() !== email.toLowerCase();

    // Only a genuine change is history; re-adding the same address is not.
    if (changed) {
      await execute("INSERT INTO member_email_history (discord_id, email) VALUES ($1, $2)", [discordId, previous]);
    }
    await execute(
      `INSERT INTO member_emails (discord_id, email, name) VALUES ($1, $2, $3)
       ON CONFLICT (discord_id) DO UPDATE
         SET email = EXCLUDED.email,
             name = COALESCE(EXCLUDED.name, member_emails.name),
             updated_at = CURRENT_TIMESTAMP`,
      [discordId, email, name],
    );

    return res.json({ ok: true, email, previous: changed ? previous : null, updated: Boolean(existing) });
  } catch {
    return res.status(503).json({ ok: false, message: "Email records need a database. Nothing was saved." });
  }
});

/** Reverse lookup: which member an address belongs to. */
router.get("/bot/search", requireBot, async (req, res) => {
  if (!(await actorMayViewEmails(str(req.query.actor)))) return forbiddenLookup(res);
  const email = str(req.query.email).trim();
  if (!email) return res.status(400).json({ ok: false, message: "Give an email to search for." });
  try {
    await ensureTables();
    const row = (
      await query('SELECT discord_id AS "discordId", name FROM member_emails WHERE LOWER(email) = LOWER($1) LIMIT 1', [
        email,
      ])
    )[0];
    if (!row) return res.json({ found: false });
    return res.json({ found: true, discordId: row.discordId, name: row.name ?? null });
  } catch {
    return res.json({ found: false });
  }
});

/** One member's email on file, with the addresses they have had before. */
router.get("/bot/:discordId", requireBot, async (req, res) => {
  if (!(await actorMayViewEmails(str(req.query.actor)))) return forbiddenLookup(res);
  const discordId = str(req.params.discordId);
  if (!/^\d{17,20}$/.test(discordId)) {
    return res.status(400).json({ ok: false, message: "That is not a Discord ID." });
  }
  try {
    await ensureTables();
    const row = (
      await query('SELECT email, name, updated_at AS "updatedAt" FROM member_emails WHERE discord_id = $1', [discordId])
    )[0];
    if (!row) return res.json({ email: null });
    const history = await query(
      'SELECT email, replaced_at AS "replacedAt" FROM member_email_history WHERE discord_id = $1 ORDER BY replaced_at DESC',
      [discordId],
    );
    return res.json({ email: row.email, name: row.name ?? null, updatedAt: row.updatedAt, history });
  } catch {
    return res.json({ email: null });
  }
});

/* ------------------------------------------------------------------ *
 * The site
 * ------------------------------------------------------------------ */

/** The whole directory, joined to the roster for name, department and rank. */
router.get("/", requirePermission("emails.view"), async (req, res) => {
  const departments = seed.DEPARTMENTS.map((d) => ({ id: d.id, label: d.label, abbr: d.abbr }));
  try {
    await ensureTables();
    // One roster row per member (their most recently synced), so a member in two
    // departments does not become two directory rows.
    const rows = await query(`
      SELECT DISTINCT ON (e.discord_id)
        e.discord_id AS "discordId", e.email, e.name, e.updated_at AS "updatedAt",
        r.character_name AS "characterName", r.display_name AS "displayName",
        r.department, r.rank_label AS "rank", r.callsign, r.status
      FROM member_emails e
      LEFT JOIN roster_members r ON r.discord_id = e.discord_id
      ORDER BY e.discord_id, r.synced_at DESC NULLS LAST`);

    const hist = await query(
      'SELECT discord_id AS "discordId", email, replaced_at AS "replacedAt" FROM member_email_history ORDER BY replaced_at DESC',
    );
    const historyBy = new Map();
    for (const h of hist) {
      if (!historyBy.has(h.discordId)) historyBy.set(h.discordId, []);
      historyBy.get(h.discordId).push({ email: h.email, replacedAt: h.replacedAt });
    }

    const members = rows
      .map((r) => ({
        discordId: r.discordId,
        email: r.email,
        name: r.displayName || r.characterName || r.name || null,
        department: r.department || null,
        rank: r.rank || null,
        callsign: r.callsign || null,
        status: r.status || null,
        updatedAt: r.updatedAt,
        history: historyBy.get(r.discordId) ?? [],
      }))
      .sort((a, b) => new Date(b.updatedAt) - new Date(a.updatedAt));

    return res.json({ members, departments });
  } catch {
    return res.json({ members: [], departments });
  }
});

export default router;
