/**
 * The /api/staff-log router — the Staff team's internal admin log.
 *
 * A private ledger kept ON staff members: resignations, LOAs, strikes,
 * terminations. It is NOT the disciplinary database — nothing here reaches a
 * member's background check — and every endpoint is gated on the one permission
 * `staff.records.manage`, which resolves to Senior Admins and up.
 *
 * A termination (or blacklist) archives the member: the row is marked archived
 * and a snapshot of what we knew about them is frozen onto it, so a former staff
 * member's record still reads as something after their roster row is cleared.
 *
 * The table is created on demand, the same way leadership_seats is, so a deploy
 * that has not re-run the schema still gets a working page rather than a 500.
 */
import { Router } from "express";
import { query, execute, changedRows } from "../db.js";
import { requirePermission } from "../middleware/requirePermission.js";
import { str } from "../validate.js";
import {
  STAFF_LOG_TYPES,
  isTerminalType,
  normalizeStaffLog,
  profileFor,
  validateStaffLog,
} from "../lib/staffLog.js";

const router = Router();

let tableReady = false;
async function ensureTable() {
  if (tableReady) return;
  await query(`CREATE TABLE IF NOT EXISTS staff_admin_logs (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY,
    type                  VARCHAR(32)  NOT NULL,
    target_name           VARCHAR(128) NOT NULL,
    target_discord_id     VARCHAR(20)  NOT NULL,
    target_rank           VARCHAR(64)  NULL,
    note                  VARCHAR(2000) NULL,
    effective_at          DATE         NULL,
    expires_at            DATE         NULL,
    logged_by_name        VARCHAR(128) NULL,
    logged_by_discord_id  VARCHAR(20)  NULL,
    archived              BOOLEAN      NOT NULL DEFAULT FALSE,
    archive_snapshot      JSONB        NULL,
    created_at            TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at            TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id)
  )`);
  await query(
    "CREATE INDEX IF NOT EXISTS idx_staff_log_target ON staff_admin_logs (target_discord_id, created_at)",
  );
  tableReady = true;
}

const COLUMNS = `
  id, type, target_name AS "targetName", target_discord_id AS "targetDiscordId",
  target_rank AS "targetRank", note, effective_at AS "effectiveAt",
  expires_at AS "expiresAt", logged_by_name AS "loggedByName",
  logged_by_discord_id AS "loggedByDiscordId", archived,
  archive_snapshot AS "archiveSnapshot", created_at AS "createdAt",
  updated_at AS "updatedAt"`;

async function loadEntries({ targetDiscordId } = {}) {
  await ensureTable();
  const where = [];
  const params = [];
  if (targetDiscordId) {
    params.push(targetDiscordId);
    where.push(`target_discord_id = $${params.length}`);
  }
  const rows = await query(
    `SELECT ${COLUMNS} FROM staff_admin_logs${where.length ? ` WHERE ${where.join(" AND ")}` : ""}
     ORDER BY created_at DESC LIMIT 2000`,
    params,
  );
  return rows.map((row) => normalizeStaffLog({ ...row, archived: Boolean(row.archived) }));
}

function noStore(res) {
  return res.status(503).json({
    ok: false,
    code: "STAFF_LOG_NO_STORE",
    message: "The admin log needs a database to record. Nothing was written.",
  });
}

// Every route here is Senior Admins+ — reading the log is as sensitive as writing it.
router.use(requirePermission("staff.records.manage"));

/* ─── Reading ──────────────────────────────────────────────────────────────── */

/** The whole log, newest first, plus the type catalogue the UI renders from. */
router.get("/", async (req, res) => {
  try {
    const entries = await loadEntries();
    return res.json({ entries, types: STAFF_LOG_TYPES });
  } catch {
    return res.json({ entries: [], types: STAFF_LOG_TYPES });
  }
});

/** One staff member's internal profile — their whole history, folded. */
router.get("/profile/:discordId", async (req, res) => {
  const discordId = str(req.params.discordId).trim();
  if (!/^\d{17,20}$/.test(discordId)) {
    return res.status(400).json({ ok: false, message: "That is not a Discord ID." });
  }
  try {
    const entries = await loadEntries({ targetDiscordId: discordId });
    return res.json({ profile: profileFor(entries, { discordId }) });
  } catch {
    return res.json({ profile: profileFor([], { discordId }) });
  }
});

/* ─── Filing ───────────────────────────────────────────────────────────────── */

router.post("/", async (req, res) => {
  const body = req.body ?? {};
  const draft = {
    type: str(body.type),
    targetName: str(body.targetName).slice(0, 128).trim(),
    targetDiscordId: str(body.targetDiscordId).trim(),
    targetRank: str(body.targetRank).slice(0, 64).trim(),
    note: str(body.note).slice(0, 2000),
    effectiveAt: body.effectiveAt || null,
    expiresAt: body.expiresAt || null,
  };

  const { errors, ok } = validateStaffLog(draft);
  if (!ok) return res.status(400).json({ ok: false, code: "STAFF_LOG_INVALID", errors });

  const user = req.user;
  const byName = user?.displayName ?? user?.username ?? "Unknown";

  // A termination or blacklist freezes what we know about the member now, before
  // their roster row is cleared — that is the archive the page reads later.
  const archived = isTerminalType(draft.type);
  const snapshot = archived
    ? {
        name: draft.targetName,
        rank: draft.targetRank || null,
        discordId: draft.targetDiscordId,
        archivedAt: new Date().toISOString(),
        by: byName,
      }
    : null;

  let created = null;
  try {
    const result = await query(
      `INSERT INTO staff_admin_logs
         (type, target_name, target_discord_id, target_rank, note, effective_at, expires_at,
          logged_by_name, logged_by_discord_id, archived, archive_snapshot)
       VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
       RETURNING ${COLUMNS}`,
      [
        draft.type,
        draft.targetName,
        draft.targetDiscordId,
        draft.targetRank || null,
        draft.note || null,
        draft.effectiveAt ? new Date(draft.effectiveAt) : null,
        draft.expiresAt ? new Date(draft.expiresAt) : null,
        byName,
        user?.id ?? null,
        archived,
        snapshot ? JSON.stringify(snapshot) : null,
      ],
    );
    created = result[0] ?? null;
  } catch {
    return noStore(res);
  }

  return res.status(201).json({
    ok: true,
    entry: normalizeStaffLog({ ...created, archived: Boolean(created?.archived) }),
  });
});

/** Remove a mistaken entry. The log is short — a typo is deleted, not voided. */
router.delete("/:id", async (req, res) => {
  const id = Number(req.params.id);
  if (!Number.isInteger(id) || id < 1) return res.status(400).json({ ok: false, message: "Invalid id." });
  try {
    await ensureTable();
    const result = await execute("DELETE FROM staff_admin_logs WHERE id = $1", [id]);
    if (!changedRows(result)) return res.status(404).json({ ok: false, message: "No such entry." });
  } catch {
    return noStore(res);
  }
  return res.json({ ok: true });
});

export default router;
